server 8080; # 8080 포트에서 요청을 기다리겠다는 뜻.
	
	client_max_body_size 1000000 #클라이언트가 서버로 보내는 데이터(업로드 등)최대 1MB까지 허용(업로드 폭주 방지, 메모리/디스크 보호, 너무 큰 POST를 미리 차단 가능)

	error_page 404 /errors/404.html # 404 상황이 생기면 기본 에러 메세지 대신 /error/404.html을 에러 화면으로 보내라는 뜻

	# 일반 웹사이트 페이지를 제공하는 구역
	location /
		root ./www/site1 # 정적 파일을 찾을 디렉토리 설정
		index index.html # 사용자가 웹사이트 경로를 요청했을 때 서버가 기본적으로 보여줄 페이지(파일)을 지정함
		autoindex off # 폴더 요청 시 index가 없거나 접근불가면 파일 목록을 자동으로 보여줄지 여부인데 off로 함으로써 에러처리(403: 접근 허용 안함)
		methods GET # 페이지 보기만 가능하고 업로드나 삭제 불가

	# 서버 파일을 목록으로 보여주고 다운로드하는 구역
	location /files
		root ./www/site1/files
		autoindex on # 파일 목록을 브라우저에 보여줌
		#ㄴ(index지시어가 없는건 메인 페이지가 아닌 파일들이 쌓여있는 디렉토리를 브라우저로 탐색(다운)하게 하는 공간이여서)
		methods GET

	# 파일 업로드하는 구역
	location /upload
		methods POST # POST는 리소스를 생성하는 메소드. 즉 서버에 데이터를 추가, 작성 등을 한다.
		upload_dir ./uploads # 파일 업로드 시 저장할 디렉토리를 지정함

	# 이 주소로 오면 다른 주소로 가라고 알려주는 리다이렉트.
	# return: 즉시 응답 만들기
	# 301: 상태코드 영구이동
	# 이동하라고 알려줄 새 URL
	# /redir했을 때 /files로 이동하면 구현이 잘된것.
	location /redir
		return 301 /files # /redir같은 곳으로 요청이 오면 서버가 거기 말고 /files로 가라는 응답을 보냄(301은 영구 이동으로 이 주소는 앞으로 항상 저쪽으로 가라는 뜻)


	# 파일을 실행해서 결과를 보내는 구역
	location /cgi-bin
		root ./cgi-bin # /cgi-bin아래에서 스크립트 파일을 찾을 폴더
		methods GET POST
		cgi_ext .py / # .py 확장자 파일은 CGI로 실행하겠다