server 9090

	client_max_body_size 1000000
	error_page 400 /errors/400.html
	connetionTimeOut 60
	readTimeout 60
	writeTimeout 60
	keepAliveTimeout 75
	cgiTimeout 60

	location /
		root /home/halee/Desktop/webserv/www
		index index.html

	location /files
		root /home/halee/Desktop/webserv/files
		autoindex on

	location /upload
		methods POST
		root /home/halee/Desktop/webserv/uploads

	location /old_stuff
		return 301 /files
		methods GET

	location /cgi_bin
		alias /home/halee/Desktop/webserv/src/cgi
		methods GET POST
		cgi_ext .py /usr/bin/python3
end
