server 8080

	client_max_body_size 1000000
	error_page 400 /errors/400.html

	connetionTimeOut 60
	readTimeout 60
	writeTimeout 60
	keepAliveTimeout 75
	cgiTimeout 60

	location /
		alias /files/root/
		index index.html

	location /files
		root /files/root
		autoindex on

	location /upload
		methods POST
		root /uploads

	location /old_stuff
		return 301 /files
		methods GET

	location /cgi_bin
		root /cgi_bin
		methods GET POST
		cgi_ext .py /
end