server 8080

	client_max_body_size 1000000
	error_page 400 ./www/error/400.html
	error_page 403 ./www/error/403.html
	error_page 404 ./www/error/404.html
	error_page 405 ./www/error/405.html
	error_page 408 ./www/error/408.html
	error_page 413 ./www/error/413.html
	error_page 414 ./www/error/414.html
	error_page 431 ./www/error/431.html
	error_page 500 ./www/error/500.html
	error_page 501 ./www/error/501.html
	error_page 502 ./www/error/502.html
	error_page 503 ./www/error/503.html
	error_page 504 ./www/error/504.html
	error_page 505 ./www/error/505.html

	connection_timeout 60
	read_timeout 60
	write_timeout 60
	keep_alive_timeout 75
	cgi_timeout 60

	location /
		alias ./www/
		index index.html

	location /upload
		methods GET POST
		alias ./www/uploads
		autoindex on

	location /old_stuff
		return 301 /
		methods GET

	location /cgi-bin
		alias ./src/cgi
		methods GET POST
		cgi_ext .py /usr/bin/python3

	location /cgi-bin/test
		alias ./tests
		methods GET POST
		cgi_ext .py /usr/bin/python3
end