# 빈줄도 언제 나올지 문법정하기
server
	listen 8080
	client_max_body_size 1000000
	error_page 404 /errors/404.html

	location /
		root ./www/site1
		index index.html
		methods GET

	location /files
		root ./www/site1/files
		autoindex on
		methods GET

	location /upload
		methods POST
		upload_dir ./uploads

	location /redir
		return 301 /files

	location /cgi-bin
		root ./cgi-bin
		methods GET POST
		cgi_ext .py /
end

server
	listen 8081
	
	client_max_body_size 1000000

	error_page 404 /errors/404.html

	location /
		root ./www/site1
		index index.html
		methods GET

	location /files
		root ./www/site1/files
		autoindex on
		methods GET

	location /upload
		methods POST
		upload_dir ./uploads

	location /redir
		return 301 /files

	location /cgi-bin
		root ./cgi-bin
		methods GET POST
		cgi_ext .py /
end
