# location 지시어 기본값이 있어도 되나에 대한 여부
# location /files에 들어갔는데 root가 없다고 기본값으로 설정해버리면 나는 파일 페이지에 들어갔는데
# 여기는 기본 페이지로 보내주자냐!!!

server 8080
	client_max_body_size 10000000
	error_page 404 /errors/404.html

	location /
		root ./www/site1
		index index.html
		methods GET POST DELETE

	location /files
		root ./www/site1/files
		autoindex on
		methods GET

	location /upload
		methods POST
		upload_dir ./uploads

	location /redir
		return 301 /files
		methods GET

	location /cgi-bin
		root ./cgi-bin
		methods GET POST
		cgi_ext .py /

	location aaa
		root ./cgi-bin
		methods GET POST
		cgi_ext .py / 
end

server 8081
	client_max_body_size 10000000
	error_page 404 /errors/404.html

	location /
		root ./www/site1
		index index.html
		methods GET POST DELETE

	location /files
		root ./www/site1/files
		autoindex on
		methods GET

	location /upload
		methods POST
		upload_dir ./uploads

	location /redir
		return 301 /files
		methods GET

	location /cgi-bin
		root ./cgi-bin
		methods GET POST
		cgi_ext .py /

	location aaa
		root ./cgi-bin
		methods GET POST
		cgi_ext .py / 
end