

server 8080
	client_max_body_size 10000000
	error_page 404 /errors/404.html

	location aa
		root ./www/site1
		index index.html
		methods GET POST DELETE

	location /files
		root ./www/site1/files
		autoindex on
		methods GET

	location /upload
		methods POST
		upload_dir ./uploads

	location /redir
		return 301 /files
		methods GET

	location /cgi-bin
		root ./cgi-bin
		methods GET POST
		cgi_ext .py /

	location aaa
		root ./cgi-bin
		methods GET POST
		cgi_ext .py / 

end

server 8080
	

end